import {
  Home,
  Compass,
  TrendingUp,
  Bell,
  MessageCircle,
  User,
  Sparkles,
  PlusSquare,
  LogOut,
  Moon,
  Sun,
  Heart,
  MessageSquare,
  Share2,
  Send,
  Search,
  Hash,
  MoreHorizontal,
  Settings,
  ArrowLeft,
  AlertTriangle,
  AtSign,
  Mail,
  Lock,
  Eye,
  EyeOff,
  Check,
  CheckCheck,
  ShieldCheck,
  Globe,
  Zap,
  Layers,
} from 'lucide-react';

export const Icons = {
  Home: (props: any) => <Home {...props} />,
  Explore: (props: any) => <Compass {...props} />,
  Trending: (props: any) => <TrendingUp {...props} />,
  Notifications: (props: any) => <Bell {...props} />,
  Messages: (props: any) => <MessageCircle {...props} />,
  Profile: (props: any) => <User {...props} />,
  ForYou: (props: any) => <Sparkles {...props} />,
  CreatePost: (props: any) => <PlusSquare {...props} />,
  Logout: (props: any) => <LogOut {...props} />,
  DarkMode: (props: any) => <Moon {...props} />,
  LightMode: (props: any) => <Sun {...props} />,
  Like: (props: any) => <Heart {...props} />,
  Comment: (props: any) => <MessageSquare {...props} />,
  Share: (props: any) => <Share2 {...props} />,
  Send: (props: any) => <Send {...props} />,
  Search: (props: any) => <Search {...props} />,
  Hash: (props: any) => <Hash {...props} />,
  More: (props: any) => <MoreHorizontal {...props} />,
  Settings: (props: any) => <Settings {...props} />,
  Back: (props: any) => <ArrowLeft {...props} />,
  Alert: (props: any) => <AlertTriangle {...props} />,
  AtSign: (props: any) => <AtSign {...props} />,
  Mail: (props: any) => <Mail {...props} />,
  Lock: (props: any) => <Lock {...props} />,
  Eye: (props: any) => <Eye {...props} />,
  EyeOff: (props: any) => <EyeOff {...props} />,
  Check: (props: any) => <Check {...props} />,
  CheckCheck: (props: any) => <CheckCheck {...props} />,
  ShieldCheck: (props: any) => <ShieldCheck {...props} />,
  Globe: (props: any) => <Globe {...props} />,
  Zap: (props: any) => <Zap {...props} />,
  Layers: (props: any) => <Layers {...props} />,
};
