import {
  Home,
  Compass,
  TrendingUp,
  Bell,
  MessageCircle,
  User,
  Sparkles,
  PlusSquare,
  LogOut,
  Moon,
  Sun,
  Heart,
  MessageSquare,
  Share2,
  Send,
  Search,
  Hash,
  MoreHorizontal,
  Settings,
} from 'lucide-react';

export const Icons = {
  Home: (props: any) => <Home {...props} />,
  Explore: (props: any) => <Compass {...props} />,
  Trending: (props: any) => <TrendingUp {...props} />,
  Notifications: (props: any) => <Bell {...props} />,
  Messages: (props: any) => <MessageCircle {...props} />,
  Profile: (props: any) => <User {...props} />,
  ForYou: (props: any) => <Sparkles {...props} />,
  CreatePost: (props: any) => <PlusSquare {...props} />,
  Logout: (props: any) => <LogOut {...props} />,
  DarkMode: (props: any) => <Moon {...props} />,
  LightMode: (props: any) => <Sun {...props} />,
  Like: (props: any) => <Heart {...props} />,
  Comment: (props: any) => <MessageSquare {...props} />,
  Share: (props: any) => <Share2 {...props} />,
  Send: (props: any) => <Send {...props} />,
  Search: (props: any) => <Search {...props} />,
  Hash: (props: any) => <Hash {...props} />,
  More: (props: any) => <MoreHorizontal {...props} />,
  Settings: (props: any) => <Settings {...props} />,
};
